inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'spec/controllers/regression/**/*'
    - 'spec/models/regression/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'db/**/*'

Style/IndentationConsistency:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/AndOr:
  EnforcedStyle: conditionals
